version: '3.8'

services:
    odoo:
        container_name: smile_addons_odoo
        environment:
          - HOST=db
          - USER=odoo
          - PASSWORD=odoo
          - _JAVA_OPTIONS=-Xmx2048m -XX:CompressedClassSpaceSize=256m -Xmx300m
        build: .
        ports:
            - 8069:8069
        stdin_open: true
        tty: true
        user: odoo
        volumes:
          - odoo-web-data:/var/lib/odoo
          - .:/mnt/extra-addons
    db:
        container_name: smile_addons_db
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_USER=odoo
          - PGDATA=/var/lib/postgresql/data/pgdata
        image: postgres:16-alpine
        ports:
            - 5432:5432
        volumes:
          - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
    odoo-db-data:
    odoo-web-data:
